### ISSUE TITLE
"--fix" mode not working?

### ISSUE THREAD

**Issue by trusktr** [mapbox/eslint-plugin-script-tags#6]
Hello,

I'm trying to use the `--fix` option with eslint, but it seems like eslint does no fixes to non-`.js` files. 

For example, it fixes `.js` files, but it makes no changes to my `.hbs` files which are being handled by eslint-plugin-script-tags.

See this issue where I described my issue and also provided a link to a reproduction: https://github.com/adametry/gulp-eslint/issues/204

Does eslint-plugin-script-tags perhaps not allow `--fix` mode to work on the target files (hbs, html, php, etc)?

**Comment by davidtheclark** [comment]
@trusktr: I don't know if or how ESLint's `--fix` mode works for plugins and processors. I'd imagine this one should work the same as any other processor, and if that means there's no `--fix`ing, there's nothing this package can do about it. If you find evidence to the contrary, though — that this package needs to do something it's not doing — we could look into it.

**Comment by trusktr** [comment]
@davidtheclark Ahah! Turns out, processors don't work with `--fix` mode by default, see this: https://github.com/eslint/eslint/issues/9142

Waiting for feedback to see if there's anything that can be done on this end.

**Comment by trusktr** [comment]
@davidtheclark Based on these [plugin docs](https://eslint.org/docs/developer-guide/working-with-plugins#testing), it seems like maybe providing some sort of `output` option is how you make a processor work with `--fix` mode?

**Comment by not-an-aardvark** [comment]
At the moment, it's not possible to make processors work with autofixing. The `output` property is used when testing rules to make assertions about how a particular rule's autofixer works, but it doesn't relate to processors.

**Comment by trusktr** [comment]
Oh okay, so pending https://github.com/eslint/eslint/pull/9090 for processors to be able to work with autofix.

In my case, I'll workaround the issue for now by running `prettier` in my own step before running `eslint`.
